name: Build and Push Docker Image
# 해당 action이 수행될 조건 / main branch에 push가 일어나면 실행
# 요청된 PR을 merge하거나 직접 push하면 action 실행
on:
  push:
    branches:
      - "main"
#pipeline 구성      
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    #디폴트로 action이 수행되는 github repo의 소스를 내려받는 기능
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    #builder driver나 platform을 세팅
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    # docker hub에 접속하기 위한 id와 password, repo의 setting에서 secrets>>action에서 action용 secret을 만들어야한다. 
    - name: Login to DockerHub
      uses: docker/login-action@v2
      #두개의 시크릿을 만들어야한다
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        #Docker hub ID/image name : version
        tags: ${{ secrets.DOCKER_ID }}/kollava:latest